### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by patrickjane** [alekseyn/iCloudStoreManager#1]
Just downloaded the package, tried to compile your project, this is the errors it gives me:

http://i42.tinypic.com/17zswp.png

Need to mention I set deployment target to 5.0, but I doubt this has anything to do with it.

**Comment by alekseyn** [comment]
Which version of Xcode are you running? It seems like ARC may have somehow got turned off? I would recommend deleting the project and downloading a fresh copy, and then running it without making any changes other than the Entitlements file and the Bundle Identifier.

**Comment by patrickjane** [comment]
Hi

I didnt make any other changes to the project, and I'm running 4.2.1 I think (the last version before 5.1 update)

So arc is the problem? I want to use your code in my existing project, where arc is disabled. This will be a problem then?

Best regards
Patrick

Am 07.04.2012 um 08:56 schrieb Aleksey Novicovreply@reply.github.com:

**Comment by alekseyn** [comment]
Yes, this is the problem. You have two options, you can either convert UbiquityStoreManager to use manual reference counting, or you can convert your project to ARC. If you decide to do the first, using Xcode's analyze feature will catch most issues. But I highly recommend converting your project to ARC. It may seem like a big task but Xcode does almost all of the work for you. I recently converted a 14,000 line project and it only took a couple of hours. And using ARC is such a massive productivity booster, I wish I had switched over sooner.

**Comment by patrickjane** [comment]
Shouldn't your project compile when I download and unzip it? I take it has arc enabled? Also I think some of the issues are not related to arc.
Nevertheless I will try to convert your code to non-arc and see what happens.
Thanks for your help.

Am 07.04.2012 um 16:26 schrieb Aleksey Novicovreply@reply.github.com:

**Comment by alekseyn** [comment]
Yes, the project should and does run as is with the latest release of Xcode, after you correctly setup the iCloud entitlements. Please make sure you are using the latest release of Xcode. If you still have problems, perform a clean build.

**Comment by patrickjane** [comment]
I updated to the latest version of xcode, cleaned everything and adjusted for non-ARC usage. Now it seems to work. Will have to test a bit to find potential zombies and stuff, but it should be okay now. Thanks for your support. Now I can check how my project does with your store manager :)

**Comment by alekseyn** [comment]
I just made an important fix. Please make sure you get the latest changes.

**Comment by lhunath** [comment]
You don't HAVE to add the iCloudStoreManager to your _application target_.  What you should do is make a _new_ target, a static library target, more specifically, and add iCloudStoreManager to _that_ target.  Then link your _application_ target against your new _iCloudStoreManager_ target.

You can then make an application that doesn't do ARC, and an iCloudStoreManager which does.
