### ISSUE TITLE
Deleting the store via Manage Storage breaks sync

### ISSUE THREAD

**Issue by lhunath** [alekseyn/iCloudStoreManager#3]
It appears that if the user deletes the iCloud storage for the application via Settings.app, the devices stop syncing.

**Comment by lhunath** [comment]
Hard resetting the cloud storage appears to resolve the issue.

Can somebody else confirm that they are also seeing this behavior?

**Comment by lhunath** [comment]
If this is correct, I should like a way to detect this case and offer the user a means of recovery.

**Comment by alekseyn** [comment]
I haven't found a way yet to detect when a user essentially nukes all of the data in iCloud. Others have commented on this general issue with iCloud and Core Data as well. As far as I know, there is no API or notification that warns an app that all of the data in the cloud is gone.

**Comment by lhunath** [comment]
Looks like we should implement this:
https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/iCloudDesignGuide/Chapters/iCloudFundametals.html#//apple_ref/doc/uid/TP40012094-CH6-SW6

**Comment by alekseyn** [comment]
The changes you elude to are confidential have to wait until iOS 6 is publicly released.

**Comment by JotWee** [comment]
:) iOS 6 is out now (hint hint)

**Comment by alekseyn** [comment]
:) I'm not sure when I will get a chance to get back to this project, hopefully soon. WHen I do, my plan is to drop support for iOS 5 and focus on iOS 6 only.
