### ISSUE TITLE
Handling merge conflicts

### ISSUE THREAD

**Issue by ghulammustafa** [alekseyn/iCloudStoreManager#6]
This is more of a query than an issue.

Are you planning to post an update that addresses resolving the merge conflicts? 
How do you propose they should be handled with UbiquityStoreManager?

**Comment by alekseyn** [comment]
There are different merge policies that can be implemented. When I eventually get back to this project I will look at merge conflicts. But my first priority will be to get a rock solid implementation for iOS 6 only.
