### ISSUE TITLE
Turning ON iCloud should check if iCloud is enabled on the device

### ISSUE THREAD

**Issue by ghulammustafa** [alekseyn/iCloudStoreManager#7]
Scenario:
- Turn OFF iCloud on the device (on iPhone or iPad).
- Open iCloudStoreManager sample application.
- iCloud is OFF by default.
- Use "+" to add some records.
- Turn iCloud to ON.

This will show an alert message, asking if we want to move the data to iCloud. Since iCloud is OFF on the device, it shouldn't show this message, and it shouldn't let the user to turn ON iCloud in the application.

Let me know if I'm missing something. Thanks.

**Comment by alekseyn** [comment]
If my memory serves me correctly, this is a use case that is now better handled with the iOS 6 iCloud API changes. I would start there. I will eventually adapt this project to iOS 6 but can't commit to a schedule right now.
