### ISSUE TITLE
Migrate fix

### ISSUE THREAD

**Issue by fbradyirl** [alekseyn/iCloudStoreManager#8]
If you constantly toggle on and off iCloud for a user, you can get UI lockups because _isReady is in the wrong state. To resolve this I have added _isReady = NO; in the following place below. I can now toggle on and off many many times without a hitch.
- (void)migrate:(BOOL)migrate andUseCloudStorageWithUUID:(NSString *)uuid completionBlock:(void (^)(BOOL usingiCloud))completionBlock {
  if (persistentStoreCoordinator__ == nil)
      persistentStoreCoordinator__ = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel: model__];
  
  if ([self.delegate respondsToSelector:@selector(ubiquityStoreManager:log:)])
      [self.delegate ubiquityStoreManager:self log:[NSString stringWithFormat:@"Setting up store with UUID: %@", uuid]];
  
  _isReady = NO;

**Comment by alekseyn** [comment]
Thanks. When I get back to this project I will test this out.
